; Data from 1605 to 1605 (1 bytes)	
A$detail_screen$60:	
C$detail_screen.c$12$0$0:	
C$detail_screen.c$15$0$0:	
G$screen_detail_screen_load$0$0:	
XG$screen_detail_screen_load$0$0:	
_screen_detail_screen_load:	
	ret
	
; Data from 1606 to 1606 (1 bytes)	
A$detail_screen$73:	
C$detail_screen.c$17$0$0:	
C$detail_screen.c$19$1$25:	
G$screen_detail_screen_update$0$:	
_screen_detail_screen_update:	
	.db $C1
	
; Data from 1607 to 1607 (1 bytes)	
A$detail_screen$74:	
	.db $E1
	
; Data from 1608 to 1608 (1 bytes)	
A$detail_screen$75:	
	.db $E5
	
; Data from 1609 to 1609 (1 bytes)	
A$detail_screen$76:	
	.db $C5
	
; Data from 160A to 160B (2 bytes)	
A$detail_screen$77:	
	.db $36 $06
	
; Data from 160C to 160C (1 bytes)	
A$detail_screen$82:	
C$detail_screen.c$20$1$25:	
XG$screen_detail_screen_update$0:	
	ret