; Data from 1655 to 1657 (3 bytes)	
A$func_screen$62:	
C$func_screen.c$15$0$0:	
C$func_screen.c$17$1$23:	
G$screen_func_screen_load$0$0:	
_screen_func_screen_load:	
	.db $CD $2B $08
	
; Data from 1658 to 165A (3 bytes)	
A$func_screen$66:	
C$func_screen.c$18$1$23:	
	.db $CD $A2 $0A
	
; Data from 165B to 165D (3 bytes)	
A$func_screen$70:	
C$func_screen.c$19$1$23:	
	.db $CD $E3 $0A
	
; Data from 165E to 1660 (3 bytes)	
A$func_screen$74:	
C$func_screen.c$20$1$23:	
	.db $CD $51 $0B
	
; Data from 1661 to 1663 (3 bytes)	
A$func_screen$78:	
C$func_screen.c$21$1$23:	
	.db $21 $06 $0C
	
; Data from 1664 to 1664 (1 bytes)	
A$func_screen$79:	
	.db $E5
	
; Data from 1665 to 1667 (3 bytes)	
A$func_screen$80:	
	.db $21 $B9 $16
	
; Data from 1668 to 1668 (1 bytes)	
A$func_screen$81:	
	.db $E5
	
; Data from 1669 to 166B (3 bytes)	
A$func_screen$82:	
	.db $CD $E9 $0D
	
; Data from 166C to 166C (1 bytes)	
A$func_screen$83:	
	.db $F1
	
; Data from 166D to 166F (3 bytes)	
A$func_screen$87:	
C$func_screen.c$22$1$23:	
	.db $21 $14 $0C
	
; Data from 1670 to 1670 (1 bytes)	
A$func_screen$88:	
	.db $E3
	
; Data from 1671 to 1673 (3 bytes)	
A$func_screen$89:	
	.db $21 $C0 $16
	
; Data from 1674 to 1674 (1 bytes)	
A$func_screen$90:	
	.db $E5
	
; Data from 1675 to 1677 (3 bytes)	
A$func_screen$91:	
	.db $CD $E9 $0D
	
; Data from 1678 to 1678 (1 bytes)	
A$func_screen$92:	
	.db $F1
	
; Data from 1679 to 1679 (1 bytes)	
A$func_screen$93:	
	.db $F1
	
; Data from 167A to 167C (3 bytes)	
A$func_screen$97:	
C$func_screen.c$24$1$23:	
	.db $21 $B8 $16
	
; Data from 167D to 167D (1 bytes)	
A$func_screen$98:	
	.db $56
	
; Data from 167E to 1680 (3 bytes)	
A$func_screen$99:	
	.db $21 $B7 $16
	
; Data from 1681 to 1681 (1 bytes)	
A$func_screen$100:	
	.db $5E
	
; Data from 1682 to 1682 (1 bytes)	
A$func_screen$101:	
	.db $D5
	
; Data from 1683 to 1685 (3 bytes)	
A$func_screen$102:	
	.db $21 $C7 $16
	
; Data from 1686 to 1686 (1 bytes)	
A$func_screen$103:	
	.db $E5
	
; Data from 1687 to 1689 (3 bytes)	
A$func_screen$104:	
	.db $CD $E9 $0D
	
; Data from 168A to 168A (1 bytes)	
A$func_screen$105:	
	.db $F1
	
; Data from 168B to 168B (1 bytes)	
A$func_screen$106:	
	.db $F1
	
; Data from 168C to 168E (3 bytes)	
A$func_screen$110:	
C$func_screen.c$25$1$23:	
	.db $21 $B8 $16
	
; Data from 168F to 168F (1 bytes)	
A$func_screen$111:	
	.db $46
	
; Data from 1690 to 1692 (3 bytes)	
A$func_screen$112:	
	.db $3A $B7 $16
	
; Data from 1693 to 1694 (2 bytes)	
A$func_screen$113:	
	.db $C6 $07
	
; Data from 1695 to 1695 (1 bytes)	
A$func_screen$114:	
	.db $4F
	
; Data from 1696 to 1696 (1 bytes)	
A$func_screen$115:	
	.db $C5
	
; Data from 1697 to 1699 (3 bytes)	
A$func_screen$116:	
	.db $21 $CC $16
	
; Data from 169A to 169A (1 bytes)	
A$func_screen$117:	
	.db $E5
	
; Data from 169B to 169D (3 bytes)	
A$func_screen$118:	
	.db $CD $E9 $0D
	
; Data from 169E to 169E (1 bytes)	
A$func_screen$119:	
	.db $F1
	
; Data from 169F to 169F (1 bytes)	
A$func_screen$120:	
	.db $F1
	
; Data from 16A0 to 16A2 (3 bytes)	
A$func_screen$124:	
C$func_screen.c$26$1$23:	
	.db $21 $B8 $16
	
; Data from 16A3 to 16A3 (1 bytes)	
A$func_screen$125:	
	.db $46
	
; Data from 16A4 to 16A6 (3 bytes)	
A$func_screen$126:	
	.db $3A $B7 $16
	
; Data from 16A7 to 16A8 (2 bytes)	
A$func_screen$127:	
	.db $C6 $0E
	
; Data from 16A9 to 16A9 (1 bytes)	
A$func_screen$128:	
	.db $4F
	
; Data from 16AA to 16AA (1 bytes)	
A$func_screen$129:	
	.db $C5
	
; Data from 16AB to 16AD (3 bytes)	
A$func_screen$130:	
	.db $21 $D1 $16
	
; Data from 16AE to 16AE (1 bytes)	
A$func_screen$131:	
	.db $E5
	
; Data from 16AF to 16B1 (3 bytes)	
A$func_screen$132:	
	.db $CD $E9 $0D
	
; Data from 16B2 to 16B2 (1 bytes)	
A$func_screen$133:	
	.db $F1
	
; Data from 16B3 to 16B3 (1 bytes)	
A$func_screen$134:	
	.db $F1
	
; Data from 16B4 to 16B6 (3 bytes)	
A$func_screen$142:	
C$func_screen.c$27$1$23:	
C$func_screen.c$32$1$23:	
XG$screen_func_screen_load$0$0:	
	.db $C3 $25 $08
	
; Data from 16B7 to 16B7 (1 bytes)	
Ffunc_screen$x$0$0:	
	.db $04
	
; Data from 16B8 to 16B8 (1 bytes)	
Ffunc_screen$y$0$0:	
	.db $14
	
; Data from 16B9 to 16BF (7 bytes)	
Ffunc_screen$__str_0$0$0:	
	.db $52 $45 $43 $4F $52 $44 $00
	
; Data from 16C0 to 16C6 (7 bytes)	
Ffunc_screen$__str_1$0$0:	
	.db $43 $4F $56 $45 $52 $53 $00
	
; Data from 16C7 to 16CB (5 bytes)	
Ffunc_screen$__str_2$0$0:	
	.db $31 $39 $38 $34 $00
	
; Data from 16CC to 16D0 (5 bytes)	
Ffunc_screen$__str_3$0$0:	
	.db $31 $39 $38 $36 $00
	
; Data from 16D1 to 16D5 (5 bytes)	
Ffunc_screen$__str_4$0$0:	
	.db $31 $39 $38 $38 $00
	
; Data from 16D6 to 16D6 (1 bytes)	
A$func_screen$181:	
C$func_screen.c$34$1$23:	
C$func_screen.c$57$1$25:	
G$screen_func_screen_update$0$0:	
_screen_func_screen_update:	
	.db $C1
	
; Data from 16D7 to 16D7 (1 bytes)	
A$func_screen$182:	
	.db $E1
	
; Data from 16D8 to 16D8 (1 bytes)	
A$func_screen$183:	
	.db $E5
	
; Data from 16D9 to 16D9 (1 bytes)	
A$func_screen$184:	
	.db $C5
	
; Data from 16DA to 16DB (2 bytes)	
A$func_screen$185:	
	.db $36 $08
	
; Data from 16DC to 16DC (1 bytes)	
A$func_screen$190:	
C$func_screen.c$58$1$25:	
XG$screen_func_screen_update$0$0:	
	.db $C9
