; Data from 122B to 122B (1 bytes)	
A$none_screen$60:	
C$none_screen.c$4$0$0:	
C$none_screen.c$6$0$0:	
G$screen_none_screen_load$0$0:	
XG$screen_none_screen_load$0$0:	
_screen_none_screen_load:	
	.db $C9
	
; Data from 122C to 122C (1 bytes)	
A$none_screen$73:	
C$none_screen.c$10$1$4:	
C$none_screen.c$8$0$0:	
G$screen_none_screen_update$0$0:	
_screen_none_screen_update:	
	.db $D1
	
; Data from 122D to 122D (1 bytes)	
A$none_screen$74:	
	.db $C1
	
; Data from 122E to 122E (1 bytes)	
A$none_screen$75:	
	.db $C5
	
; Data from 122F to 122F (1 bytes)	
A$none_screen$76:	
	.db $D5
	
; Data from 1230 to 1230 (1 bytes)	
A$none_screen$77:	
	.db $AF
	
; Data from 1231 to 1231 (1 bytes)	
A$none_screen$78:	
	.db $02
	
; Data from 1232 to 1232 (1 bytes)	
A$none_screen$83:	
C$none_screen.c$11$1$4:	
XG$screen_none_screen_update$0$0:	
	.db $C9