; Data from 1480 to 1482 (3 bytes)	
A$select_screen$86:	
C$select_screen.c$22$0$0:	
C$select_screen.c$24$1$29:	
C$select_screen.c$25$1$29:	
G$screen_select_screen_load$0$0:	
_screen_select_screen_load:	
	.db $3A $51 $C0
	
; Data from 1483 to 1483 (1 bytes)	
A$select_screen$87:	
	.db $B7
	
; Data from 1484 to 1485 (2 bytes)	
A$select_screen$88:	
	.db $20 $2B
	
; Data from 1486 to 1488 (3 bytes)	
A$select_screen$92:	
C$select_screen.c$27$2$30:	
	.db $CD $2B $08
	
; Data from 1489 to 148B (3 bytes)	
A$select_screen$96:	
C$select_screen.c$28$2$30:	
	.db $CD $5A $0A
	
; Data from 148C to 148E (3 bytes)	
A$select_screen$100:	
C$select_screen.c$29$2$30:	
	.db $CD $A2 $0A
	
; Data from 148F to 1491 (3 bytes)	
A$select_screen$104:	
C$select_screen.c$30$2$30:	
	.db $CD $1A $0B
	
; Data from 1492 to 1494 (3 bytes)	
A$select_screen$108:	
C$select_screen.c$31$2$30:	
	.db $CD $51 $0B
	
; Data from 1495 to 1497 (3 bytes)	
A$select_screen$112:	
C$select_screen.c$33$2$30:	
	.db $21 $06 $08
	
; Data from 1498 to 1498 (1 bytes)	
A$select_screen$113:	
	.db $E5
	
; Data from 1499 to 149B (3 bytes)	
A$select_screen$114:	
	.db $21 $D5 $14
	
; Data from 149C to 149C (1 bytes)	
A$select_screen$115:	
	.db $E5
	
; Data from 149D to 149F (3 bytes)	
A$select_screen$116:	
	.db $CD $E9 $0D
	
; Data from 14A0 to 14A0 (1 bytes)	
A$select_screen$117:	
	.db $F1
	
; Data from 14A1 to 14A3 (3 bytes)	
A$select_screen$121:	
C$select_screen.c$34$2$30:	
	.db $21 $14 $08
	
; Data from 14A4 to 14A4 (1 bytes)	
A$select_screen$122:	
	.db $E3
	
; Data from 14A5 to 14A7 (3 bytes)	
A$select_screen$123:	
	.db $21 $DC $14
	
; Data from 14A8 to 14A8 (1 bytes)	
A$select_screen$124:	
	.db $E5
	
; Data from 14A9 to 14AB (3 bytes)	
A$select_screen$125:	
	.db $CD $E9 $0D
	
; Data from 14AC to 14AC (1 bytes)	
A$select_screen$126:	
	.db $F1
	
; Data from 14AD to 14AD (1 bytes)	
A$select_screen$127:	
	.db $F1
	
; Data from 14AE to 14B0 (3 bytes)	
A$select_screen$131:	
C$select_screen.c$35$2$30:	
	.db $CD $25 $08
	
; Data from 14B1 to 14B3 (3 bytes)	
A$select_screen$136:	
C$select_screen.c$38$1$29:	
	.db $21 $51 $C0
	
; Data from 14B4 to 14B4 (1 bytes)	
A$select_screen$137:	
	.db $46
	
; Data from 14B5 to 14B5 (1 bytes)	
A$select_screen$138:	
	.db $C5
	
; Data from 14B6 to 14B6 (1 bytes)	
A$select_screen$139:	
	.db $33
	
; Data from 14B7 to 14B9 (3 bytes)	
A$select_screen$140:	
	.db $CD $9B $0B
	
; Data from 14BA to 14BA (1 bytes)	
A$select_screen$141:	
	.db $33
	
; Data from 14BB to 14BD (3 bytes)	
A$select_screen$145:	
C$select_screen.c$40$1$29:	
	.db $21 $0F $00
	
; Data from 14BE to 14BE (1 bytes)	
A$select_screen$146:	
	.db $E5
	
; Data from 14BF to 14C1 (3 bytes)	
A$select_screen$147:	
	.db $CD $63 $11
	
; Data from 14C2 to 14C4 (3 bytes)	
A$select_screen$151:	
C$select_screen.c$41$1$29:	
	.db $21 $4B $00
	
; Data from 14C5 to 14C5 (1 bytes)	
A$select_screen$152:	
	.db $E3
	
; Data from 14C6 to 14C8 (3 bytes)	
A$select_screen$153:	
	.db $CD $9E $11
	
; Data from 14C9 to 14C9 (1 bytes)	
A$select_screen$154:	
	.db $F1
	
; Data from 14CA to 14CC (3 bytes)	
A$select_screen$158:	
C$select_screen.c$43$1$29:	
	.db $21 $63 $C0
	
; Data from 14CD to 14CE (2 bytes)	
A$select_screen$159:	
	.db $36 $00
	
; Data from 14CF to 14D1 (3 bytes)	
A$select_screen$163:	
C$select_screen.c$44$1$29:	
	.db $21 $64 $C0
	
; Data from 14D2 to 14D3 (2 bytes)	
A$select_screen$164:	
	.db $36 $01
	
; Data from 14D4 to 14D4 (1 bytes)	
A$select_screen$169:	
C$select_screen.c$45$1$29:	
XG$screen_select_screen_load$0$0:	
	.db $C9
	
; Data from 14D5 to 14DB (7 bytes)	
Fselect_screen$__str_0$0$0:	
	.db $52 $45 $43 $4F $52 $44 $00
	
; Data from 14DC to 14E2 (7 bytes)	
Fselect_screen$__str_1$0$0:	
	.db $43 $4F $56 $45 $52 $53 $00
	
; Data from 14E3 to 14E5 (3 bytes)	
A$select_screen$190:	
C$select_screen.c$47$1$29:	
C$select_screen.c$54$1$32:	
G$screen_select_screen_update$0$:	
_screen_select_screen_update:	
	.db $3A $63 $C0
	
; Data from 14E6 to 14E6 (1 bytes)	
A$select_screen$191:	
	.db $3D
	
; Data from 14E7 to 14E8 (2 bytes)	
A$select_screen$192:	
	.db $20 $2A
	
; Data from 14E9 to 14EB (3 bytes)	
A$select_screen$196:	
C$select_screen.c$56$2$33:	
	.db $3A $64 $C0
	
; Data from 14EC to 14EC (1 bytes)	
A$select_screen$197:	
	.db $B7
	
; Data from 14ED to 14EE (2 bytes)	
A$select_screen$198:	
	.db $28 $03
	
; Data from 14EF to 14F1 (3 bytes)	
A$select_screen$202:	
C$select_screen.c$58$3$34:	
	.db $CD $13 $0C
	
; Data from 14F2 to 14F4 (3 bytes)	
A$select_screen$207:	
C$select_screen.c$61$2$33:	
	.db $CD $7C $11
	
; Data from 14F5 to 14F5 (1 bytes)	
A$select_screen$211:	
C$select_screen.c$62$2$33:	
	.db $7D
	
; Data from 14F6 to 14F6 (1 bytes)	
A$select_screen$212:	
	.db $B7
	
; Data from 14F7 to 14F8 (2 bytes)	
A$select_screen$213:	
	.db $28 $07
	
; Data from 14F9 to 14FB (3 bytes)	
A$select_screen$217:	
C$select_screen.c$64$3$35:	
	.db $21 $64 $C0
	
; Data from 14FC to 14FD (2 bytes)	
A$select_screen$218:	
	.db $3E $01
	
; Data from 14FE to 14FE (1 bytes)	
A$select_screen$219:	
	.db $96
	
; Data from 14FF to 14FF (1 bytes)	
A$select_screen$220:	
	.db $77
	
; Data from 1500 to 1502 (3 bytes)	
A$select_screen$225:	
C$select_screen.c$67$2$33:	
	.db $CD $B3 $11
	
; Data from 1503 to 1503 (1 bytes)	
A$select_screen$229:	
C$select_screen.c$68$2$33:	
	.db $D1
	
; Data from 1504 to 1504 (1 bytes)	
A$select_screen$230:	
	.db $C1
	
; Data from 1505 to 1505 (1 bytes)	
A$select_screen$231:	
	.db $C5
	
; Data from 1506 to 1506 (1 bytes)	
A$select_screen$232:	
	.db $D5
	
; Data from 1507 to 1507 (1 bytes)	
A$select_screen$233:	
	.db $7D
	
; Data from 1508 to 1508 (1 bytes)	
A$select_screen$234:	
	.db $B7
	
; Data from 1509 to 150A (2 bytes)	
A$select_screen$235:	
	.db $28 $04
	
; Data from 150B to 150C (2 bytes)	
A$select_screen$236:	
	.db $3E $05
	
; Data from 150D to 150E (2 bytes)	
A$select_screen$237:	
	.db $18 $02
	
; Data from 150F to 1510 (2 bytes)	
A$select_screen$239:	
	.db $3E $04
	
; Data from 1511 to 1511 (1 bytes)	
A$select_screen$241:	
	.db $02
	
; Data from 1512 to 1512 (1 bytes)	
A$select_screen$245:	
C$select_screen.c$69$2$33:	
	.db $C9
	
; Data from 1513 to 1515 (3 bytes)	
A$select_screen$250:	
C$select_screen.c$72$1$32:	
	.db $CD $13 $0C
	
; Data from 1516 to 1517 (2 bytes)	
A$select_screen$254:	
C$select_screen.c$74$1$32:	
	.db $3E $10
	
; Data from 1518 to 1518 (1 bytes)	
A$select_screen$255:	
	.db $F5
	
; Data from 1519 to 1519 (1 bytes)	
A$select_screen$256:	
	.db $33
	
; Data from 151A to 151C (3 bytes)	
A$select_screen$257:	
	.db $CD $D3 $0E
	
; Data from 151D to 151D (1 bytes)	
A$select_screen$258:	
	.db $33
	
; Data from 151E to 151E (1 bytes)	
A$select_screen$262:	
C$select_screen.c$75$1$32:	
	.db $7D
	
; Data from 151F to 151F (1 bytes)	
A$select_screen$263:	
	.db $B7
	
; Data from 1520 to 1521 (2 bytes)	
A$select_screen$264:	
	.db $28 $13
	
; Data from 1522 to 1524 (3 bytes)	
A$select_screen$268:	
C$select_screen.c$77$2$36:	
	.db $CD $05 $0C
	
; Data from 1525 to 1525 (1 bytes)	
A$select_screen$269:	
	.db $45
	
; Data from 1526 to 1526 (1 bytes)	
A$select_screen$273:	
C$select_screen.c$78$2$36:	
	.db $C5
	
; Data from 1527 to 1527 (1 bytes)	
A$select_screen$274:	
	.db $33
	
; Data from 1528 to 152A (3 bytes)	
A$select_screen$275:	
	.db $CD $7D $0F
	
; Data from 152B to 152B (1 bytes)	
A$select_screen$276:	
	.db $33
	
; Data from 152C to 152E (3 bytes)	
A$select_screen$280:	
C$select_screen.c$81$2$36:	
	.db $CD $70 $0A
	
; Data from 152F to 1531 (3 bytes)	
A$select_screen$284:	
C$select_screen.c$82$2$36:	
	.db $21 $63 $C0
	
; Data from 1532 to 1533 (2 bytes)	
A$select_screen$285:	
	.db $36 $01
	
; Data from 1534 to 1534 (1 bytes)	
A$select_screen$289:	
C$select_screen.c$83$2$36:	
	.db $C9
	
; Data from 1535 to 1536 (2 bytes)	
A$select_screen$294:	
C$select_screen.c$86$1$32:	
	.db $3E $04
	
; Data from 1537 to 1537 (1 bytes)	
A$select_screen$295:	
	.db $F5
	
; Data from 1538 to 1538 (1 bytes)	
A$select_screen$296:	
	.db $33
	
; Data from 1539 to 153B (3 bytes)	
A$select_screen$297:	
	.db $CD $D3 $0E
	
; Data from 153C to 153C (1 bytes)	
A$select_screen$298:	
	.db $33
	
; Data from 153D to 153D (1 bytes)	
A$select_screen$302:	
C$select_screen.c$87$1$32:	
	.db $7D
	
; Data from 153E to 153E (1 bytes)	
A$select_screen$303:	
	.db $B7
	
; Data from 153F to 1540 (2 bytes)	
A$select_screen$304:	
	.db $28 $03
	
; Data from 1541 to 1543 (3 bytes)	
A$select_screen$308:	
C$select_screen.c$89$2$37:	
	.db $CD $3E $0D
	
; Data from 1544 to 1545 (2 bytes)	
A$select_screen$313:	
C$select_screen.c$91$1$32:	
	.db $3E $08
	
; Data from 1546 to 1546 (1 bytes)	
A$select_screen$314:	
	.db $F5
	
; Data from 1547 to 1547 (1 bytes)	
A$select_screen$315:	
	.db $33
	
; Data from 1548 to 154A (3 bytes)	
A$select_screen$316:	
	.db $CD $D3 $0E
	
; Data from 154B to 154B (1 bytes)	
A$select_screen$317:	
	.db $33
	
; Data from 154C to 154C (1 bytes)	
A$select_screen$321:	
C$select_screen.c$92$1$32:	
	.db $7D
	
; Data from 154D to 154D (1 bytes)	
A$select_screen$322:	
	.db $B7
	
; Data from 154E to 154F (2 bytes)	
A$select_screen$323:	
	.db $28 $03
	
; Data from 1550 to 1552 (3 bytes)	
A$select_screen$327:	
C$select_screen.c$94$2$38:	
	.db $CD $51 $0D
	
; Data from 1553 to 1554 (2 bytes)	
A$select_screen$332:	
C$select_screen.c$96$1$32:	
	.db $3E $01
	
; Data from 1555 to 1555 (1 bytes)	
A$select_screen$333:	
	.db $F5
	
; Data from 1556 to 1556 (1 bytes)	
A$select_screen$334:	
	.db $33
	
; Data from 1557 to 1559 (3 bytes)	
A$select_screen$335:	
	.db $CD $D3 $0E
	
; Data from 155A to 155A (1 bytes)	
A$select_screen$336:	
	.db $33
	
; Data from 155B to 155B (1 bytes)	
A$select_screen$340:	
C$select_screen.c$97$1$32:	
	.db $7D
	
; Data from 155C to 155C (1 bytes)	
A$select_screen$341:	
	.db $B7
	
; Data from 155D to 155E (2 bytes)	
A$select_screen$342:	
	.db $28 $03
	
; Data from 155F to 1561 (3 bytes)	
A$select_screen$346:	
C$select_screen.c$99$2$39:	
	.db $CD $63 $0D
	
; Data from 1562 to 1563 (2 bytes)	
A$select_screen$351:	
C$select_screen.c$101$1$32:	
	.db $3E $02
	
; Data from 1564 to 1564 (1 bytes)	
A$select_screen$352:	
	.db $F5
	
; Data from 1565 to 1565 (1 bytes)	
A$select_screen$353:	
	.db $33
	
; Data from 1566 to 1568 (3 bytes)	
A$select_screen$354:	
	.db $CD $D3 $0E
	
; Data from 1569 to 1569 (1 bytes)	
A$select_screen$355:	
	.db $33
	
; Data from 156A to 156A (1 bytes)	
A$select_screen$359:	
C$select_screen.c$102$1$32:	
	.db $7D
	
; Data from 156B to 156B (1 bytes)	
A$select_screen$360:	
	.db $B7
	
; Data from 156C to 156D (2 bytes)	
A$select_screen$361:	
	.db $28 $03
	
; Data from 156E to 1570 (3 bytes)	
A$select_screen$365:	
C$select_screen.c$104$2$40:	
	.db $CD $76 $0D
	
; Data from 1571 to 1571 (1 bytes)	
A$select_screen$370:	
C$select_screen.c$107$1$32:	
	.db $C1
	
; Data from 1572 to 1572 (1 bytes)	
A$select_screen$371:	
	.db $E1
	
; Data from 1573 to 1573 (1 bytes)	
A$select_screen$372:	
	.db $E5
	
; Data from 1574 to 1574 (1 bytes)	
A$select_screen$373:	
	.db $C5
	
; Data from 1575 to 1576 (2 bytes)	
A$select_screen$374:	
	.db $36 $04
	
; Data from 1577 to 1577 (1 bytes)	
A$select_screen$379:	
C$select_screen.c$108$1$32:	
XG$screen_select_screen_update$0:	
	.db $C9