; Data from 160D to 160F (3 bytes)	
A$test_screen$65:	
C$test_screen.c$13$0$0:	
C$test_screen.c$15$1$23:	
G$screen_test_screen_load$0$0:	
_screen_test_screen_load:	
	.db $CD $2B $08
	
; Data from 1610 to 1612 (3 bytes)	
A$test_screen$69:	
C$test_screen.c$16$1$23:	
	.db $CD $E3 $0A
	
; Data from 1613 to 1615 (3 bytes)	
A$test_screen$73:	
C$test_screen.c$17$1$23:	
	.db $21 $0A $15
	
; Data from 1616 to 1616 (1 bytes)	
A$test_screen$74:	
	.db $E5
	
; Data from 1617 to 1619 (3 bytes)	
A$test_screen$75:	
	.db $21 $29 $16
	
; Data from 161A to 161A (1 bytes)	
A$test_screen$76:	
	.db $E5
	
; Data from 161B to 161D (3 bytes)	
A$test_screen$77:	
	.db $CD $E9 $0D
	
; Data from 161E to 161E (1 bytes)	
A$test_screen$78:	
	.db $F1
	
; Data from 161F to 161F (1 bytes)	
A$test_screen$79:	
	.db $F1
	
; Data from 1620 to 1622 (3 bytes)	
A$test_screen$83:	
C$test_screen.c$18$1$23:	
	.db $CD $25 $08
	
; Data from 1623 to 1625 (3 bytes)	
A$test_screen$87:	
C$test_screen.c$20$1$23:	
	.db $21 $66 $C0
	
; Data from 1626 to 1627 (2 bytes)	
A$test_screen$88:	
	.db $36 $00
	
; Data from 1628 to 1628 (1 bytes)	
A$test_screen$93:	
C$test_screen.c$21$1$23:	
XG$screen_test_screen_load$0$0:	
	.db $C9
	
; Data from 1629 to 1634 (12 bytes)	
Ftest_screen$__str_0$0$0:	
	.db $50 $52 $45 $53 $53 $20 $53 $54 $41 $52 $54 $00
	
; Data from 1635 to 1636 (2 bytes)	
A$test_screen$110:	
C$test_screen.c$23$1$23:	
C$test_screen.c$28$1$25:	
G$screen_test_screen_update$0$0:	
_screen_test_screen_update:	
	.db $3E $02
	
; Data from 1637 to 1637 (1 bytes)	
A$test_screen$111:	
	.db $F5
	
; Data from 1638 to 1638 (1 bytes)	
A$test_screen$112:	
	.db $33
	
; Data from 1639 to 163B (3 bytes)	
A$test_screen$113:	
	.db $CD $00 $0F
	
; Data from 163C to 163C (1 bytes)	
A$test_screen$114:	
	.db $33
	
; Data from 163D to 163D (1 bytes)	
A$test_screen$118:	
C$test_screen.c$29$1$25:	
	.db $7D
	
; Data from 163E to 163E (1 bytes)	
A$test_screen$119:	
	.db $B7
	
; Data from 163F to 1640 (2 bytes)	
A$test_screen$120:	
	.db $28 $0D
	
; Data from 1641 to 1643 (3 bytes)	
A$test_screen$124:	
C$test_screen.c$32$2$26:	
	.db $3A $66 $C0
	
; Data from 1644 to 1644 (1 bytes)	
A$test_screen$125:	
	.db $F5
	
; Data from 1645 to 1645 (1 bytes)	
A$test_screen$126:	
	.db $33
	
; Data from 1646 to 1648 (3 bytes)	
A$test_screen$127:	
	.db $CD $46 $08
	
; Data from 1649 to 1649 (1 bytes)	
A$test_screen$128:	
	.db $33
	
; Data from 164A to 164C (3 bytes)	
A$test_screen$132:	
C$test_screen.c$34$2$26:	
	.db $21 $66 $C0
	
; Data from 164D to 164D (1 bytes)	
A$test_screen$133:	
	.db $34
	
; Data from 164E to 164E (1 bytes)	
A$test_screen$138:	
C$test_screen.c$38$1$25:	
	.db $C1
	
; Data from 164F to 164F (1 bytes)	
A$test_screen$139:	
	.db $E1
	
; Data from 1650 to 1650 (1 bytes)	
A$test_screen$140:	
	.db $E5
	
; Data from 1651 to 1651 (1 bytes)	
A$test_screen$141:	
	.db $C5
	
; Data from 1652 to 1653 (2 bytes)	
A$test_screen$142:	
	.db $36 $07
	
; Data from 1654 to 1654 (1 bytes)	
A$test_screen$147:	
C$test_screen.c$39$1$25:	
XG$screen_test_screen_update$0$0:	
	.db $C9