; Data from F7D to F7F (3 bytes)	
A$record_manager$69:	
C$record_manager.c$12$0$0:	
C$record_manager.c$14$1$19:	
C$record_manager.c$15$1$19:	
G$engine_record_manager_init$0$0:	
_engine_record_manager_init:	
	.db $21 $2A $C0
	
; Data from F80 to F83 (4 bytes)	
A$record_manager$70:	
	.db $FD $21 $02 $00
	
; Data from F84 to F85 (2 bytes)	
A$record_manager$71:	
	.db $FD $39
	
; Data from F86 to F88 (3 bytes)	
A$record_manager$72:	
	.db $FD $7E $00
	
; Data from F89 to F89 (1 bytes)	
A$record_manager$73:	
	.db $77
	
; Data from F8A to F8A (1 bytes)	
A$record_manager$78:	
C$record_manager.c$16$1$19:	
XG$engine_record_manager_init$0$:	
	.db $C9
	
; Data from F8B to F8C (2 bytes)	
A$record_manager$88:	
C$record_manager.c$17$1$19:	
G$engine_record_manager_load$0$0:	
_engine_record_manager_load:	
	.db $DD $E5
	
; Data from F8D to F90 (4 bytes)	
A$record_manager$89:	
	.db $DD $21 $00 $00
	
; Data from F91 to F92 (2 bytes)	
A$record_manager$90:	
	.db $DD $39
	
; Data from F93 to F93 (1 bytes)	
A$record_manager$91:	
	.db $3B
	
; Data from F94 to F96 (3 bytes)	
A$record_manager$98:	
C$record_manager.c$19$1$20:	
C$record_manager.c$20$1$20:	
	.db $3A $2A $C0
	
; Data from F97 to F99 (3 bytes)	
A$record_manager$102:	
C$record_manager.c$22$1$20:	
	.db $DD $77 $FF
	
; Data from F9A to F9A (1 bytes)	
A$record_manager$103:	
	.db $6F
	
; Data from F9B to F9C (2 bytes)	
A$record_manager$104:	
	.db $26 $00
	
; Data from F9D to F9D (1 bytes)	
A$record_manager$105:	
	.db $29
	
; Data from F9E to F9E (1 bytes)	
A$record_manager$106:	
	.db $4D
	
; Data from F9F to F9F (1 bytes)	
A$record_manager$107:	
	.db $44
	
; Data from FA0 to FA2 (3 bytes)	
A$record_manager$108:	
	.db $21 $6E $C1
	
; Data from FA3 to FA3 (1 bytes)	
A$record_manager$109:	
	.db $09
	
; Data from FA4 to FA4 (1 bytes)	
A$record_manager$110:	
	.db $5E
	
; Data from FA5 to FA5 (1 bytes)	
A$record_manager$111:	
	.db $23
	
; Data from FA6 to FA6 (1 bytes)	
A$record_manager$112:	
	.db $56
	
; Data from FA7 to FA9 (3 bytes)	
A$record_manager$116:	
C$record_manager.c$23$1$20:	
	.db $21 $86 $C1
	
; Data from FAA to FAA (1 bytes)	
A$record_manager$117:	
	.db $09
	
; Data from FAB to FAB (1 bytes)	
A$record_manager$118:	
	.db $4E
	
; Data from FAC to FAC (1 bytes)	
A$record_manager$119:	
	.db $23
	
; Data from FAD to FAD (1 bytes)	
A$record_manager$120:	
	.db $46
	
; Data from FAE to FB0 (3 bytes)	
A$record_manager$124:	
C$record_manager.c$24$1$20:	
	.db $DD $7E $FF
	
; Data from FB1 to FB2 (2 bytes)	
A$record_manager$125:	
	.db $C6 $1F
	
; Data from FB3 to FB3 (1 bytes)	
A$record_manager$126:	
	.db $6F
	
; Data from FB4 to FB5 (2 bytes)	
A$record_manager$127:	
	.db $3E $00
	
; Data from FB6 to FB7 (2 bytes)	
A$record_manager$128:	
	.db $CE $12
	
; Data from FB8 to FB8 (1 bytes)	
A$record_manager$129:	
	.db $67
	
; Data from FB9 to FB9 (1 bytes)	
A$record_manager$130:	
	.db $66
	
; Data from FBA to FBA (1 bytes)	
A$record_manager$134:	
C$record_manager.c$26$1$20:	
	.db $C5
	
; Data from FBB to FBB (1 bytes)	
A$record_manager$135:	
	.db $D5
	
; Data from FBC to FBC (1 bytes)	
A$record_manager$136:	
	.db $E5
	
; Data from FBD to FBD (1 bytes)	
A$record_manager$137:	
	.db $33
	
; Data from FBE to FC0 (3 bytes)	
A$record_manager$138:	
	.db $CD $31 $08
	
; Data from FC1 to FC1 (1 bytes)	
A$record_manager$139:	
	.db $33
	
; Data from FC2 to FC2 (1 bytes)	
A$record_manager$140:	
	.db $D1
	
; Data from FC3 to FC5 (3 bytes)	
A$record_manager$141:	
	.db $21 $00 $00
	
; Data from FC6 to FC6 (1 bytes)	
A$record_manager$142:	
	.db $E5
	
; Data from FC7 to FC7 (1 bytes)	
A$record_manager$143:	
	.db $D5
	
; Data from FC8 to FCA (3 bytes)	
A$record_manager$144:	
	.db $CD $8E $08
	
; Data from FCB to FCB (1 bytes)	
A$record_manager$145:	
	.db $F1
	
; Data from FCC to FCE (3 bytes)	
A$record_manager$146:	
	.db $21 $00 $00
	
; Data from FCF to FCF (1 bytes)	
A$record_manager$147:	
	.db $E3
	
; Data from FD0 to FD2 (3 bytes)	
A$record_manager$148:	
	.db $CD $A4 $08
	
; Data from FD3 to FD3 (1 bytes)	
A$record_manager$149:	
	.db $F1
	
; Data from FD4 to FD4 (1 bytes)	
A$record_manager$150:	
	.db $F1
	
; Data from FD5 to FD7 (3 bytes)	
A$record_manager$154:	
C$record_manager.c$31$1$20:	
	.db $2A $9E $C1
	
; Data from FD8 to FD8 (1 bytes)	
A$record_manager$155:	
	.db $E5
	
; Data from FD9 to FDB (3 bytes)	
A$record_manager$156:	
	.db $CD $C5 $08
	
; Data from FDC to FDC (1 bytes)	
A$record_manager$157:	
	.db $F1
	
; Data from FDD to FDD (1 bytes)	
A$record_manager$158:	
	.db $33
	
; Data from FDE to FDF (2 bytes)	
A$record_manager$159:	
	.db $DD $E1
	
; Data from FE0 to FE0 (1 bytes)	
A$record_manager$164:	
C$record_manager.c$32$1$20:	
XG$engine_record_manager_load$0$:	
	.db $C9
	
; Data from FE1 to FE3 (3 bytes)	
A$record_manager$177:	
C$record_manager.c$34$1$20:	
C$record_manager.c$36$1$21:	
G$engine_record_manager_decremen:	
_engine_record_manager_decrement:	
	.db $01 $2A $C0
	
; Data from FE4 to FE4 (1 bytes)	
A$record_manager$181:	
C$record_manager.c$37$1$21:	
	.db $0A
	
; Data from FE5 to FE5 (1 bytes)	
A$record_manager$182:	
	.db $B7
	
; Data from FE6 to FE7 (2 bytes)	
A$record_manager$183:	
	.db $20 $04
	
; Data from FE8 to FE9 (2 bytes)	
A$record_manager$187:	
C$record_manager.c$39$2$22:	
	.db $3E $0B
	
; Data from FEA to FEA (1 bytes)	
A$record_manager$188:	
	.db $02
	
; Data from FEB to FEB (1 bytes)	
A$record_manager$189:	
	.db $C9
	
; Data from FEC to FED (2 bytes)	
A$record_manager$194:	
C$record_manager.c$43$2$23:	
	.db $C6 $FF
	
; Data from FEE to FEE (1 bytes)	
A$record_manager$195:	
	.db $02
	
; Data from FEF to FEF (1 bytes)	
A$record_manager$200:	
C$record_manager.c$45$1$21:	
XG$engine_record_manager_decreme:	
	.db $C9
	
; Data from FF0 to FF2 (3 bytes)	
A$record_manager$213:	
C$record_manager.c$46$1$21:	
C$record_manager.c$48$1$24:	
G$engine_record_manager_incremen:	
_engine_record_manager_increment:	
	.db $01 $2A $C0
	
; Data from FF3 to FF3 (1 bytes)	
A$record_manager$217:	
C$record_manager.c$49$1$24:	
	.db $0A
	
; Data from FF4 to FF5 (2 bytes)	
A$record_manager$218:	
	.db $FE $0B
	
; Data from FF6 to FF7 (2 bytes)	
A$record_manager$219:	
	.db $20 $03
	
; Data from FF8 to FF8 (1 bytes)	
A$record_manager$223:	
C$record_manager.c$51$2$25:	
	.db $AF
	
; Data from FF9 to FF9 (1 bytes)	
A$record_manager$224:	
	.db $02
	
; Data from FFA to FFA (1 bytes)	
A$record_manager$225:	
	.db $C9
	
; Data from FFB to FFB (1 bytes)	
A$record_manager$230:	
C$record_manager.c$55$2$26:	
	.db $3C
	
; Data from FFC to FFC (1 bytes)	
A$record_manager$231:	
	.db $02
	
; Data from FFD to FFD (1 bytes)	
A$record_manager$236:	
C$record_manager.c$57$1$24:	
XG$engine_record_manager_increme:	
	.db $C9